import { ServerConnections } from 'lib/jellyfin-apiclient';
import Dashboard from 'utils/dashboard';
import { playbackManager } from 'components/playback/playbackmanager';
import { homeflixApi } from './api';
import { node, action, iconAction, icon, select, safeImage, readUser, storeUser, readSession, storeSession, empty } from './ui';
import { mediaGrid, mediaSection } from './cards';
import { createCarousel } from './carousel';
import { createAI } from './ai';
import { createDetails } from './details';
import { libraryFilterFields, libraryParams, openFilters, filterCount, filterChips } from './filters';
import './homeflix.scss';

const librarySorts=[['SortName','Title'],['Random','Random'],['CommunityRating','Community rating'],['CriticRating','Critic rating'],['DateCreated','Date added'],['DatePlayed','Last played'],['OfficialRating','Parental rating'],['PlayCount','Play count'],['PremiereDate','Release date'],['Runtime','Runtime']];

export function createHomeflix(root) {
    let client,userId,active=false,generation=0,pageController,searchTimer,details,carouselCleanup,aiCleanup,returnDetails,loggedOut=false,upcomingGeneration=-1;
    let libraries=[],catalogAllowed=false,requestReady=false,integrationReady=false,discoveryFields={},currentView='home',selectedLibrary='',discoverView='discover',language='english',restoreScroll=0,restoreSearch='';
    const browsing=new Map(),aiState={prompt:'',source:'library',scope:'general',language:'english',type:'movie',items:[]};
    const app=node('div','hf-app');const nav=node('nav','hf-nav');nav.setAttribute('aria-label','Main navigation');
    const brand=action('HomeFlix',()=>navigate('home'),'hf-brand');brand.append(node('span','hf-brand-dot'));
    const tools=node('div','hf-user-tools');const header=node('header','hf-header',brand,nav,tools);
    const main=node('main');const aiHost=node('div','hf-ai-host');const hero=node('section','hf-hero');hero.hidden=true;const content=node('div','hf-content');
    const heading=node('h1','hf-page-title');const controls=node('div','hf-controls');const status=node('div','hf-status');status.setAttribute('role','status');const results=node('div','hf-results');const shortcuts=node('div','hf-library-shortcuts');
    const search=node('input');search.type='search';search.placeholder='Search your library';search.setAttribute('aria-label','Search your library');const searchBox=node('div','hf-search',search,iconAction('Clear search',()=>{search.value='';navigate(currentView);},'close'));searchBox.hidden=true;
    content.append(node('div','hf-page-heading',heading,searchBox),shortcuts,status,controls,results);main.append(aiHost,hero,content);app.append(header,main,node('footer','hf-footer',node('span','','HomeFlix'),node('span','','LAN preview')));root.replaceChildren(app);
    const userKey=part=>`homeflix.${part}.${client.serverId()}.${userId}`;
    const loadList=()=>readUser(userKey('list'),[]).slice(0,200);
    const savedId=item=>item.library?`jf:${item.id}`:`tmdb:${item.type}:${item.id || item.tmdbId}`;
    const isSaved=item=>loadList().some(x=>x.key===savedId(item));
    function toggleList(item){const entries=loadList();const id=savedId(item);const index=entries.findIndex(x=>x.key===id);if(index>=0)entries.splice(index,1);else entries.push({key:id,id:item.id || item.tmdbId,type:item.type,library:!!item.library,scope:currentView==='libraries'&&libraries.find(x=>x.id===selectedLibrary)?.vivamax?selectedLibrary:'general'});storeUser(userKey('list'),entries.slice(-200));}
    const api=(path,body,signal)=>homeflixApi(path,body,{client,signal:signal || pageController?.signal});
    const image=(raw,type='Primary')=>safeImage(client.getImageUrl(raw.Id,{type,maxWidth:type==='Backdrop'?1600:480,quality:90}));
    function normalize(raw){const episode=raw.Type==='Episode';const seriesImage=episode&&raw.SeriesId&&raw.SeriesPrimaryImageTag?client.getImageUrl(raw.SeriesId,{type:'Primary',tag:raw.SeriesPrimaryImageTag,maxWidth:480}):null;return {id:raw.Id,title:episode?`${raw.SeriesName || raw.Name} · ${raw.Name}`:raw.Name,year:raw.ProductionYear,overview:raw.Overview || '',genres:raw.Genres || [],rating:raw.CommunityRating,type:raw.Type==='Movie'?'movie':'tv',library:true,jellyfinId:raw.Id,poster:safeImage(seriesImage || image(raw)),backdrop:image(raw,episode?'Primary':'Backdrop'),progress:raw.UserData?.PlayedPercentage || 0,episodeLabel:episode?`S${raw.ParentIndexNumber || 0} E${raw.IndexNumber || 0}`:'',raw};}
    const query=(options={})=>client.getItems(userId,{Recursive:true,Fields:'Overview,Genres,ProviderIds,People,MediaSources,Studios,DateCreated',EnableUserData:true,Limit:40,...options});
    function allowedViews(id='general'){return id==='general'?libraries.filter(x=>!x.vivamax):libraries.filter(x=>x.id===id);}
    function filterGeneral(items){return items.filter(raw=>!(raw.Studios || []).some(studio=>/\b(?:vivamax|vmx)\b/i.test(studio.Name || '')));}
    async function scopedQuery(id,options={}){const views=allowedViews(id).filter(x=>!options.IncludeItemTypes || options.IncludeItemTypes==='Episode'&&x.kind==='Series' || options.IncludeItemTypes.split(',').includes(x.kind));const batches=await Promise.allSettled(views.map(view=>query({...options,ParentId:view.id})));const items=[...new Map(batches.filter(x=>x.status==='fulfilled').flatMap(x=>x.value.Items || []).map(raw=>[raw.Id,raw])).values()];if(!batches.some(x=>x.status==='fulfilled')&&views.length)throw new Error('Your library is temporarily unavailable. Try again.');const visible=id==='general'?filterGeneral(items):items;if(options.SortBy==='DateCreated')visible.sort((a,b)=>Date.parse(b.DateCreated || 0)-Date.parse(a.DateCreated || 0));return visible.slice(0,options.Limit || 40);}
    async function resumeItems(id='general'){const batches=await Promise.allSettled(allowedViews(id).map(view=>client.ajax({type:'GET',url:client.getUrl(`Users/${userId}/Items/Resume`,{ParentId:view.id,Limit:12,MediaTypes:'Video',Fields:'Overview,Genres,ProviderIds,Studios'}),dataType:'json'})));const raw=[...new Map(batches.filter(x=>x.status==='fulfilled').flatMap(x=>x.value.Items || []).map(item=>[item.Id,item])).values()];return (id==='general'?filterGeneral(raw):raw).slice(0,12).map(normalize);}
    function rememberLanguage(value){language=value;aiState.language=value;storeUser(userKey('language'),value);}
    function viewDetails(item){details.show(item);}
    async function play(item,options){if(!item.raw || item.raw.Type==='Series'){viewDetails(item);return;}returnDetails=item;details.close();try{await playbackManager.play({ids:[item.raw.Id],serverId:client.serverId(),startPositionTicks:item.raw.UserData?.PlaybackPositionTicks || 0,...options});}catch(error){status.textContent=error.message;returnDetails=null;}}
    async function hydrate(items,library=false){if(!library)return items;const ids=items.map(item=>item.id).filter(Boolean);if(!ids.length)return [];const data=await query({Ids:ids.join(','),IncludeItemTypes:'Movie,Series,Episode',Limit:ids.length});return data.Items.map(normalize);}
    function mountAI(host,scope='general'){if(scope==='general'&&libraries.find(x=>x.id===aiState.scope)?.vivamax)aiState.scope='general';aiCleanup=createAI(host,{state:aiState,libraries,scope,catalogAllowed,requestReady,api,hydrate,details:viewDetails,onLanguage:rememberLanguage,onScope:id=>{if(libraries.find(x=>x.id===id)?.vivamax){selectedLibrary=id;navigate('libraries');}}});}
    async function upcoming(ticket){if(!catalogAllowed||ticket!==generation||currentView!=='home'||upcomingGeneration===ticket)return;upcomingGeneration=ticket;try{const data=await api('upcoming');if(active&&ticket===generation){const grouped=new Map();data.items.forEach(item=>{const key=`${item.type}:${item.tmdbId || item.title}`;if(!grouped.has(key))grouped.set(key,{...item,id:item.tmdbId,title:item.title.split(' · S')[0]});});const section=mediaSection('Coming Soon',[...grouped.values()].slice(0,16),viewDetails);section.dataset.upcoming='true';results.append(section);}}catch{/* Optional release metadata never blocks browsing. */}}
    function clear(){generation++;pageController?.abort();pageController=new AbortController();carouselCleanup?.();aiCleanup?.();carouselCleanup=null;aiCleanup=null;aiHost.replaceChildren();hero.replaceChildren();hero.hidden=true;heading.textContent='';controls.replaceChildren();results.replaceChildren();shortcuts.replaceChildren();status.textContent='';}
    function renderShortcuts(){libraries.forEach(view=>shortcuts.append(action(view.name,()=>{selectedLibrary=view.id;navigate('libraries');},`hf-library-chip${view.id===selectedLibrary&&currentView==='libraries'?' hf-selected':''}`)));}
    async function home(){const ticket=generation;heading.textContent='';mountAI(aiHost);renderShortcuts();status.textContent='Loading your library…';const [movies,resume,episodes]=await Promise.allSettled([scopedQuery('general',{IncludeItemTypes:'Movie',SortBy:'DateCreated',SortOrder:'Descending',Limit:24}),resumeItems(),scopedQuery('general',{IncludeItemTypes:'Episode',SortBy:'DateCreated',SortOrder:'Descending',Limit:40})]);if(!active||ticket!==generation)return;status.textContent='';const latest=movies.status==='fulfilled'?movies.value.map(normalize):[];carouselCleanup=createCarousel(hero,latest,{play,details:viewDetails});if(resume.status==='fulfilled'&&resume.value.length)results.append(mediaSection('Continue Watching',resume.value,viewDetails,undefined,true));results.append(mediaSection('New movies',latest,viewDetails,()=>{selectedLibrary=libraries.find(x=>x.name==='Movies')?.id || '';navigate('libraries');}));
        const specials=libraries.filter(view=>/filipino|anime/i.test(view.name));await Promise.allSettled(specials.map(async view=>{const raw=await scopedQuery(view.id,{IncludeItemTypes:view.kind,SortBy:'DateCreated',SortOrder:'Descending',Limit:12});if(active&&ticket===generation)results.append(mediaSection(view.name,raw.map(normalize),viewDetails,()=>{selectedLibrary=view.id;navigate('libraries');}));}));
        if(active&&ticket===generation&&episodes.status==='fulfilled'){const grouped=new Map();episodes.value.forEach(raw=>{if(!raw.SeriesId)return;const existing=grouped.get(raw.SeriesId);if(existing)existing.count++;else grouped.set(raw.SeriesId,{raw,count:1});});const series=await Promise.allSettled([...grouped.values()].slice(0,12).map(async({raw,count})=>{const full=await client.getItem(userId,raw.SeriesId);return {...normalize(full),episodeLabel:`${count} new episode${count>1?'s':''}`};}));if(active&&ticket===generation&&series.some(x=>x.status==='fulfilled'))results.append(mediaSection('Series updates',series.filter(x=>x.status==='fulfilled').map(x=>x.value),viewDetails));}
        await upcoming(ticket);
        if(movies.status==='rejected')status.textContent=movies.reason.message;
    }
    function browseState(id){if(!browsing.has(id))browsing.set(id,{...readUser(userKey(`filters.${id}`),{SortBy:'SortName',SortOrder:'Ascending'}),page:1,mode:'titles'});return browsing.get(id);}
    async function browse(){if(!selectedLibrary || !libraries.some(x=>x.id===selectedLibrary))selectedLibrary=libraries.find(x=>!x.vivamax)?.id;const view=libraries.find(x=>x.id===selectedLibrary);heading.textContent=view?.name || 'Libraries';renderShortcuts();if(!view){results.append(empty('No accessible libraries.'));return;}const state=browseState(view.id);const ticket=generation;let fields=libraryFilterFields({},[],view.kind);let page=1,loading=false;
        if(view.vivamax){mountAI(aiHost,view.id);try{const continued=await resumeItems(view.id);if(active&&ticket===generation&&continued.length)results.append(mediaSection('Continue Watching · Vivamax',continued,viewDetails,undefined,true));const saved=loadList().filter(item=>item.library).map(item=>item.id);if(saved.length){const items=await scopedQuery(view.id,{Ids:saved.join(','),IncludeItemTypes:'Movie,Series',Limit:200});if(active&&ticket===generation&&items.length)results.append(mediaSection('My List · Vivamax',items.map(normalize),viewDetails));}if(requestReady){const entries=loadList().filter(item=>!item.library&&item.scope===view.id).slice(0,20);(async()=>{const saved=[];for(let start=0;start<entries.length&&active&&ticket===generation;start+=4){const batch=await Promise.allSettled(entries.slice(start,start+4).map(entry=>api(`requests/details?id=${entry.id}&type=${entry.type}`)));saved.push(...batch.filter(result=>result.status==='fulfilled').map(result=>result.value.item));if(batch.some(result=>result.status==='rejected'&&result.reason.status===401))break;}if(active&&ticket===generation&&saved.length)results.append(mediaSection('Saved discovery · Vivamax',saved,viewDetails));})().catch(()=>{});}}catch{/* Optional rails remain independent of browsing. */}}
        const gridHost=node('div','hf-library-results');results.append(gridHost);const count=node('span','hf-result-count');const sortOptions=[...librarySorts,...(view.kind==='Series'?[['DateLastContentAdded','Latest episode added'],['SeriesDatePlayed','Series last played']]:[])];
        const sort=select('Sort library',sortOptions,state.SortBy,value=>{state.SortBy=value;load(true);});const direction=select('Sort direction',[['Ascending','Ascending'],['Descending','Descending']],state.SortOrder,value=>{state.SortOrder=value;load(true);});
        const filterButton=action('Filters',()=>openFilters({title:`Filter ${view.name}`,fields,values:state,lookup:async()=>[],onApply:values=>{Object.assign(state,values);Object.keys(state).filter(key=>!['SortBy','SortOrder','page','mode'].includes(key)&&!Object.hasOwn(values,key)).forEach(key=>delete state[key]);load(true);}}),'hf-button','sliders');const chips=node('div');const reset=action('Reset',()=>{browsing.delete(view.id);storeUser(userKey(`filters.${view.id}`),{SortBy:'SortName',SortOrder:'Ascending'});navigate('libraries');},'hf-text-button');controls.append(sort,direction,filterButton,reset,count,chips);
        if(view.kind==='Series')controls.prepend(select('Browse series or episodes',[['titles','Series'],['episodes','Episodes']],state.mode,value=>{state.mode=value;navigate('libraries');}));
        const type=state.mode==='episodes'?'Episode':view.kind;
        Promise.allSettled([client.ajax({type:'GET',url:client.getUrl('Items/Filters',{UserId:userId,ParentId:view.id,IncludeItemTypes:type}),dataType:'json'}),client.ajax({type:'GET',url:client.getUrl('Items/Filters2',{UserId:userId,ParentId:view.id,IncludeItemTypes:type}),dataType:'json'}),client.ajax({type:'GET',url:client.getUrl('Studios',{UserId:userId,ParentId:view.id,IncludeItemTypes:type}),dataType:'json'})]).then(data=>{if(ticket!==generation)return;const first=data[0].status==='fulfilled'?data[0].value:{};const second=data[1].status==='fulfilled'?data[1].value:{};fields=libraryFilterFields({...first,...second},data[2].status==='fulfilled'?data[2].value.Items || []:[],type);updateChips();});
        function updateChips(){filterButton.replaceChildren(`Filters${filterCount(fields,state)?` (${filterCount(fields,state)})`:''}`);chips.replaceChildren(filterChips(fields,state,name=>{delete state[name];load(true);}));}
        async function load(resetPage){if(loading)return;loading=true;if(resetPage){page=1;state.page=1;gridHost.replaceChildren();}status.textContent='Loading titles…';updateChips();storeUser(userKey(`filters.${view.id}`),state);try{const data=await query({ParentId:view.id,IncludeItemTypes:type,StartIndex:(page-1)*40,...libraryParams(state)});if(!active||ticket!==generation)return;gridHost.querySelector('.hf-more')?.remove();gridHost.append(mediaGrid(data.Items.map(normalize),viewDetails));count.textContent=`${data.TotalRecordCount || 0} titles`;status.textContent='';state.page=page;if(page*40<data.TotalRecordCount)gridHost.append(action('Load more',()=>{page++;load(false);},'hf-button hf-more'));}catch(error){if(active&&ticket===generation)status.textContent=error.message;}finally{loading=false;}}
        const previousPage=Math.min(state.page || 1,10);await load(true);for(let i=2;i<=previousPage&&active&&ticket===generation;i++){page=i;await load(false);}
    }
    async function reconnect(){heading.textContent='Connect Requests';const form=node('form','hf-reconnect',node('h2','','Connect your Requests account'),node('p','hf-muted','Sign in with your Jellyfin account to discover and request titles.'));const name=node('input');name.placeholder='Username';name.autocomplete='username';name.required=true;name.setAttribute('aria-label','Requests username');const password=node('input');password.type='password';password.placeholder='Password';password.autocomplete='current-password';password.required=true;password.setAttribute('aria-label','Requests password');const submit=node('button','hf-button hf-primary','Connect Requests');submit.type='submit';form.append(name,password,submit);results.append(form);form.addEventListener('submit',async event=>{event.preventDefault();submit.disabled=true;try{await api('requests/login',{username:name.value,password:password.value});requestReady=true;sessionStorage.removeItem('homeflix.requests.error');navigate('discover');}catch(error){status.textContent=error.message;}finally{password.value='';submit.disabled=false;}});}
    async function discover(){heading.textContent=currentView==='requests'?'My Requests':'Discover';if(!integrationReady){results.append(empty('Connecting discovery…'));return;}if(!catalogAllowed){results.append(empty('Discovery is unavailable for this profile.','Your permitted Jellyfin libraries remain available.'));return;}if(!requestReady){await reconnect();return;}const ticket=generation;let page=1;const view=currentView==='requests'?'mine':discoverView;const state=browseState(`discover.${view}`);let fields=discoveryFields[view] || [];const gridHost=node('div');results.append(gridHost);const chips=node('div');
        if(view!=='mine'){const tabs=node('div','hf-tabs');[['discover','Trending'],['movies','Movies'],['series','Series']].forEach(([id,label])=>{const tab=action(label,()=>{discoverView=id;navigate('discover');},'hf-tab');tab.setAttribute('aria-selected',String(id===view));tabs.append(tab);});controls.append(tabs,action('My Requests',()=>navigate('requests'),'hf-text-button'));if(view!=='discover'){const sortField=fields.find(x=>x.name==='sortBy');controls.append(select('Sort discovery',Object.entries(sortField.options),state.sortBy || sortField.default,value=>{state.sortBy=value;load(true);}),action(`Filters${filterCount(fields,state)?` (${filterCount(fields,state)})`:''}`,()=>openFilters({title:'Discover filters',fields,values:state,lookup:async(kind,q,signal,draft)=>(await api(`requests/lookup?${new URLSearchParams({kind,type:view==='series'?'tv':'movie',...(q?{q}:{}),...(kind==='providers'?{region:draft.watchRegion || 'PH'}:{})})}`,undefined,signal)).items,onApply:values=>{browsing.set(`discover.${view}`,{...values,page:1});navigate('discover');}}),'hf-button','sliders'),action('Reset',()=>{browsing.delete(`discover.${view}`);storeUser(userKey(`filters.discover.${view}`),{});navigate('discover');},'hf-text-button'),chips);}}
        async function load(resetPage){if(resetPage){page=1;gridHost.replaceChildren();}status.textContent='Loading the catalog…';chips.replaceChildren(filterChips(fields,state,name=>{delete state[name];load(true);}));storeUser(userKey(`filters.discover.${view}`),state);try{const params=new URLSearchParams({view,page:String(page)});if(view!=='discover'&&view!=='mine')fields.forEach(field=>{if(state[field.name])params.set(field.name,state[field.name]);});const data=await api(view==='mine'?`requests/mine?page=${page}`:`requests/browse?${params}`);if(!active||ticket!==generation)return;status.textContent='';gridHost.querySelector('.hf-more')?.remove();if(view==='mine'){data.items.forEach(item=>gridHost.append(node('article','hf-request-row',node('div','',node('h3','',item.title || `Request ${item.id}`),node('p','hf-muted',item.status)),action('Details',()=>viewDetails({id:item.mediaId,type:item.type,title:item.title || 'Requested title'})))));if(!data.items.length)gridHost.append(empty('No requests yet.'));}else gridHost.append(mediaGrid(data.items,viewDetails));if(data.nextPage)gridHost.append(action('Load more',()=>{page=data.nextPage;load(false);},'hf-button hf-more'));}catch(error){if(error.name!=='AbortError'&&active&&ticket===generation){if(error.status===401){requestReady=false;results.replaceChildren();reconnect();}status.textContent=error.message;}}}
        await load(true);
    }
    async function myList(){heading.textContent='My List';const ticket=generation;const entries=loadList(),items=[];const ids=entries.filter(x=>x.library).map(x=>x.id);if(ids.length){const data=await query({Ids:ids.join(','),IncludeItemTypes:'Movie,Series,Episode',Limit:200});const general=new Set((await scopedQuery('general',{Ids:ids.join(','),IncludeItemTypes:'Movie,Series,Episode',Limit:200})).map(x=>x.Id));items.push(...data.Items.filter(raw=>general.has(raw.Id)).map(normalize));}if(catalogAllowed&&requestReady){for(const entry of entries.filter(x=>!x.library&&!libraries.find(view=>view.id===x.scope)?.vivamax).slice(0,40)){try{const data=await api(`requests/details?id=${entry.id}&type=${entry.type}`);items.push(data.item);}catch{/* Missing titles stay hidden. */}if(ticket!==generation)return;}}if(ticket===generation){results.append(items.length?mediaGrid(items,viewDetails):empty('Your watchlist starts here.','Open a title and add it to My List.'));const vivamax=libraries.find(view=>view.vivamax);if(vivamax)controls.append(action('Vivamax watchlist',()=>{selectedLibrary=vivamax.id;navigate('libraries');},'hf-text-button'));}}
    async function navigate(view){clearTimeout(searchTimer);details?.close();clear();currentView=view;search.value='';searchBox.hidden=true;nav.querySelectorAll('button').forEach(button=>button.setAttribute('aria-current',button.dataset.view===view?'page':'false'));try{if(view==='home')await home();else if(view==='libraries')await browse();else if(view==='list')await myList();else await discover();}catch(error){if(error.name!=='AbortError')status.textContent=error.message;}}
    [['home','Home'],['libraries','Libraries'],['discover','Discover'],['list','My List']].forEach(([view,label])=>{const button=action(label,()=>navigate(view),'hf-nav-link');button.dataset.view=view;nav.append(button);});
    const profile=node('details','hf-profile');const summary=node('summary','hf-icon-button');summary.setAttribute('aria-label','Account menu');summary.append(icon('user'));const menu=node('div','hf-profile-menu',action('My Requests',()=>{profile.open=false;navigate('requests');},'hf-menu-item'),action('Settings',()=>{profile.open=false;Dashboard.navigate('mypreferencesdisplay');},'hf-menu-item'),action('Refresh',()=>{profile.open=false;navigate(currentView);},'hf-menu-item'),action('Sign out',async()=>{loggedOut=true;details?.destroy();try{await homeflixApi('requests/logout',{}, {client});}catch{/* Jellyfin logout remains available. */}sessionStorage.removeItem('homeflix.requests.error');sessionStorage.removeItem(userKey('navigation'));aiState.items=[];Dashboard.logout();},'hf-menu-item'));profile.append(summary,menu);
    tools.append(iconAction('Search library',()=>{searchBox.hidden=!searchBox.hidden;if(!searchBox.hidden){search.placeholder=currentView==='libraries'&&libraries.find(x=>x.id===selectedLibrary)?.vivamax?'Search Vivamax':'Search your library';search.focus();content.scrollIntoView({block:'start',behavior:'smooth'});}},'search'),profile);
    async function searchTitles(){const term=search.value.trim();if(term.length<2)return;const view=currentView==='libraries'&&libraries.find(x=>x.id===selectedLibrary)?.vivamax?selectedLibrary:'general';const ticket=++generation;carouselCleanup?.();aiCleanup?.();aiHost.replaceChildren();hero.hidden=true;controls.replaceChildren();shortcuts.replaceChildren();results.replaceChildren();heading.textContent=view==='general'?'Search results':'Search Vivamax';status.textContent='Searching…';try{const items=await scopedQuery(view,{SearchTerm:term,IncludeItemTypes:'Movie,Series',Limit:80});if(ticket!==generation)return;results.append(mediaGrid(items.map(normalize),viewDetails));status.textContent='';if(catalogAllowed&&requestReady&&view==='general')results.append(action('Search Discover',async()=>{status.textContent='Searching Discover…';try{const data=await api(`requests/search?q=${encodeURIComponent(term)}`);if(ticket===generation){results.append(mediaSection('Discover results',data.items,viewDetails));status.textContent='';}}catch(error){status.textContent=error.message;}},'hf-button'));}catch(error){status.textContent=error.message;}}
    search.addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(searchTitles,300);});search.addEventListener('keydown',event=>{if(event.key==='Enter'){clearTimeout(searchTimer);searchTitles();}});
    return {
        async onResume(){active=true;client=ServerConnections.currentApiClient();const first=!userId;userId=client.getCurrentUserId();if(first){const saved=readSession(userKey('navigation'),{});currentView=saved.view || 'home';selectedLibrary=saved.library || '';discoverView=saved.discover || 'discover';restoreScroll=saved.scroll || 0;restoreSearch=saved.search || '';(saved.browsing || []).forEach(([key,value])=>browsing.set(key,value));if(saved.ai)Object.assign(aiState,saved.ai);if(saved.returnId){try{returnDetails=normalize(await client.getItem(userId,saved.returnId));}catch{/* A removed or inaccessible item is not reopened. */}}}language=readUser(userKey('language'),'english');aiState.language=language;document.documentElement.classList.add('homeflix-active');const ticket=generation;
            details?.destroy();details=createDetails({client,userId,api,normalize,play,isSaved,toggleList,getLanguage:()=>language,setLanguage:rememberLanguage});
            try{const local=await client.getUserViews({},userId);libraries=(local.Items || []).filter(x=>['movies','tvshows'].includes(x.CollectionType)&&!/preroll/i.test(x.Name)).map(x=>({id:x.Id,name:/anime/i.test(x.Name)?'Anime Series':x.Name,kind:x.CollectionType==='tvshows'?'Series':'Movie',vivamax:/\b(?:vivamax|vmx)\b/i.test(x.Name)}));}catch{/* Gateway configuration can also provide authorized views. */}
            const configPromise=homeflixApi('config',undefined,{client,signal:AbortSignal.timeout(10000)}).then(config=>{catalogAllowed=config.catalogAllowed;libraries=config.libraries || libraries;discoveryFields=config.discoveryFilters || {};return homeflixApi('requests/session',undefined,{client,signal:AbortSignal.timeout(10000)}).then(()=>{requestReady=true;},()=>{requestReady=false;});}).catch(()=>{catalogAllowed=false;requestReady=false;}).finally(()=>{integrationReady=true;});
            if(!active || ticket!==generation)return;await navigate(currentView);if(restoreSearch){searchBox.hidden=false;search.value=restoreSearch;restoreSearch='';await searchTitles();}if(restoreScroll){root.closest('.page')?.scrollTo(0,restoreScroll);window.scrollTo(0,restoreScroll);restoreScroll=0;}if(returnDetails&&active){const item=returnDetails;returnDetails=null;details.show(item);}
            const rendered=generation;configPromise.then(()=>{if(!active)return;if(rendered===generation&&currentView==='home')upcoming(rendered);if(['discover','requests'].includes(currentView)&&results.querySelector('.hf-empty'))navigate(currentView);else if(rendered===generation&&!document.activeElement?.closest('.hf-ai')&&!document.querySelector('dialog[open]')&&!aiState.busy&&['home','libraries'].includes(currentView)){const scope=currentView==='libraries'&&libraries.find(x=>x.id===selectedLibrary)?.vivamax?selectedLibrary:'general';if(currentView==='home'||scope!=='general'){aiCleanup?.();aiHost.replaceChildren();mountAI(aiHost,scope);}}});
        },
        onPause(){restoreScroll=root.closest('.page')?.scrollTop || window.scrollY;restoreSearch=search.value;if(userId&&!loggedOut)storeSession(userKey('navigation'),{view:currentView,library:selectedLibrary,discover:discoverView,scroll:restoreScroll,search:restoreSearch,browsing:[...browsing],returnId:returnDetails?.id,ai:{prompt:aiState.prompt,source:aiState.source,scope:aiState.scope,type:aiState.type,language:aiState.language}});active=false;generation++;pageController?.abort();clearTimeout(searchTimer);carouselCleanup?.();aiCleanup?.();details?.close();document.documentElement.classList.remove('homeflix-active');},
        destroy(){this.onPause();details?.destroy();root.replaceChildren();}
    };
}
